name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install sqlc
        run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Go mod download
        run: go mod download

      - name: Build plugin
        run: go build -o bin/sqlc-gen-crystal

      - name: Upload plugin binary
        uses: actions/upload-artifact@v4
        with:
          name: sqlc-gen-crystal
          path: bin/sqlc-gen-crystal

      - name: Run Go tests
        run: make test-go

      - name: Download plugin binary
        uses: actions/download-artifact@v4
        with:
          name: sqlc-gen-crystal
          path: bin

      - name: Add plugin to PATH
        run: |
          chmod +x bin/sqlc-gen-crystal
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Generate examples
        run: make generate-examples

      - name: Run integration tests
        run: make test-crystal

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Go mod download
        run: go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
